### ISSUE TITLE
add IJCV paper

### ISSUE THREAD

**Issue by sinhasaptarshi** [GZWQ/Awesome-Long-Tailed#1]
Hi. Can you please add the paper 'Class-Difficulty Based Methods for Long-Tailed Visual Recognition' (https://doi.org/10.48550/arXiv.2207.14499), which was accepted in IJCV this year?

**Comment by GZWQ** [comment]
Hi, thanks for sharing the paper. Been added to the list.

**Comment by sinhasaptarshi** [comment]
thank you.
